name: Renovate
on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:
jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - id: github-app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          client-id: ${{ secrets.APP_CLIENT_ID }}
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          token: '${{ steps.github-app-token.outputs.token }}'
        env:
          RENOVATE_REPOSITORIES: '${{ github.repository }}'
